<template>
    <div class="form-container">
        <el-form :model="formData" label-width="180px" ref="formRef">
            <!-- 基本信息部分 -->
            <el-card class="form-section">
                <template #header>
                    <span class="section-title">{{ t('ssl.basicInfo') }}</span>
                </template>

                <el-form-item :label="t('ssl.certId')" prop="id" disabled>
                    <el-input v-model="formData.id" :placeholder="t('ssl.enterCertId')" />
                    <span class="form-item-tip">{{ t('ssl.autoGenerated') }}</span>
                </el-form-item>

                <el-form-item :label="t('ssl.status')" prop="status">
                    <el-radio-group v-model="formData.status">
                        <el-radio :label="1">{{ t('ssl.enabled') }}</el-radio>
                        <el-radio :label="0">{{ t('ssl.disabled') }}</el-radio>
                    </el-radio-group>
                </el-form-item>

                <el-form-item :label="t('ssl.certType')" prop="type">
                    <el-radio-group v-model="formData.type">
                        <el-radio label="server">{{ t('ssl.serverCert') }}</el-radio>
                        <el-radio label="client">{{ t('ssl.clientCert') }}</el-radio>
                    </el-radio-group>
                </el-form-item>
            </el-card>

            <!-- 证书配置部分 -->
            <el-card class="form-section">
                <template #header>
                    <span class="section-title">{{ t('ssl.certConfig') }}</span>
                </template>

                <el-form-item :label="t('ssl.certContent')" prop="cert" required>
                    <el-input v-model="formData.cert" type="textarea" :rows="5" :placeholder="t('ssl.enterCertContent')" />
                    <span class="form-item-tip">{{ t('ssl.certContentTip') }}</span>
                </el-form-item>

                <el-form-item :label="t('ssl.keyContent')" prop="key" required>
                    <el-input v-model="formData.key" type="textarea" :rows="5" :placeholder="t('ssl.enterKeyContent')" />
                    <span class="form-item-tip">{{ t('ssl.keyContentTip') }}</span>
                </el-form-item>

                <el-form-item :label="t('ssl.domainList')" prop="snis" required>
                    <array-input v-model="formData.snis" placeholder="example.com" />
                    <span class="form-item-tip">{{ t('ssl.sniTip') }}</span>
                </el-form-item>

                <el-divider content-position="left">{{ t('ssl.extraCerts') }}</el-divider>

                <el-form-item :label="t('ssl.extraCerts')">
                    <el-button type="primary" @click="addExtraCert" plain size="small">{{ t('ssl.addExtraCert') }}</el-button>
                    <span class="form-item-tip">{{ t('ssl.extraCertTip') }}</span>
                </el-form-item>

                <div v-for="(cert, index) in formData.certs" :key="'cert-' + index" class="extra-cert-item">
                    <el-divider content-position="left">{{ t('ssl.extraCertNum').replace('{num}', index + 1) }}</el-divider>
                    <el-form-item :label="'cert #' + (index + 1)" :prop="'certs.' + index">
                        <div class="cert-input-group">
                            <el-input v-model="formData.certs[index]" type="textarea" :rows="3"
                                :placeholder="t('ssl.enterCertContent')" />
                            <el-button type="danger" @click="removeExtraCert(index)" icon="Delete" circle />
                        </div>
                    </el-form-item>
                    <el-form-item :label="'key #' + (index + 1)" :prop="'keys.' + index">
                        <el-input v-model="formData.keys[index]" type="textarea" :rows="3"
                            :placeholder="t('ssl.enterKeyContent')" />
                    </el-form-item>
                </div>
            </el-card>

            <!-- 客户端证书验证配置 -->
            <el-card class="form-section">
                <template #header>
                    <span class="section-title">{{ t('ssl.clientCertVerification') }}</span>
                </template>

                <el-form-item :label="t('ssl.clientCaCert')" prop="client.ca">
                    <el-input v-model="formData.client.ca" type="textarea" :rows="5" :placeholder="t('ssl.enterClientCaCert')" />
                    <span class="form-item-tip">{{ t('ssl.clientCaCertTip') }}</span>
                </el-form-item>

                <el-form-item :label="t('ssl.verificationDepth')" prop="client.depth">
                    <el-input-number v-model="formData.client.depth" :min="0" :max="10" controls-position="right" style="width: 100%;" />
                    <span class="form-item-tip">{{ t('ssl.verificationDepthTip') }}</span>
                </el-form-item>

                <el-form-item :label="t('ssl.skipMtlsUriRegex')" prop="client.skip_mtls_uri_regex">
                    <array-input v-model="formData.client.skip_mtls_uri_regex" placeholder="/api/public/.*" />
                    <span class="form-item-tip">{{ t('ssl.skipMtlsUriRegexTip') }}</span>
                </el-form-item>
            </el-card>

            <!-- 高级配置 -->
            <el-card class="form-section">
                <template #header>
                    <span class="section-title">{{ t('ssl.advancedConfig') }}</span>
                </template>

                <el-form-item :label="t('ssl.sslProtocols')" prop="ssl_protocols">
                    <array-input v-model="formData.ssl_protocols" placeholder="TLSv1.2"
                        :options="sslProtocolOptions" />
                    <span class="form-item-tip">{{ t('ssl.sslProtocolsTip') }}</span>
                </el-form-item>

                <el-form-item :label="t('ssl.certLabels')" prop="labels">
                    <key-value-input @send-data="updateLabels" v-model="formData.labels" :key-placeholder="t('form.keyPlaceholder')"
                        :value-placeholder="t('form.valuePlaceholder')" />
                    <span class="form-item-tip">{{ t('ssl.certLabelsTip') }}</span>
                </el-form-item>
            </el-card>

            <!-- 表单操作 -->
            <div class="form-actions">
                <el-button type="primary" @click="submitForm">{{ t('common.submit') }}</el-button>
                <el-button @click="resetForm">{{ t('common.reset') }}</el-button>
            </div>
        </el-form>
    </div>
</template>

<script setup>
import { ref, reactive, defineProps, watch } from "vue";
import { getSslsById } from "@/api/module/ssl.js";
import keys from "../../../public/keys.js";
import {
    ElButton,
    ElCard,
    ElInput,
    ElInputNumber,
    ElForm,
    ElFormItem,
    ElRadioGroup,
    ElRadio,
    ElDivider,
    ElMessage,
} from "element-plus";

// 导入自定义组件
import ArrayInput from "@/components/ArrayInput.vue";
import KeyValueInput from "@/components/KeyValueInput.vue";
import { createSsls, PatchSsls } from "@/api/module/ssl.js";
import { getNonEmptyValues } from "@/utils/index.js";
import { useI18nUtils } from '@/utils/i18n.js';

// 初始表单数据
const initialFormData = {
    id: "",
    cert: keys.public,
    key: keys.private,
    certs: [],
    keys: [],
    snis: ["example.com"],
    type: "server",
    status: 1,
    ssl_protocols: [],
    labels: {},
    client: {
        ca: "",
        depth: 1,
        skip_mtls_uri_regex: []
    }
};

// 表单数据
const formData = reactive(JSON.parse(JSON.stringify(initialFormData)));

// 表单引用
const formRef = ref();
const { t } = useI18nUtils();

const props = defineProps({
    patch: {
        type: String,
        default: "",
    },
});

// 监听patch属性变化，加载已有SSL数据
watch(() => props.patch, (newValue) => {
    // 重置表单数据
    if (newValue === "") {
        Object.assign(formData, JSON.parse(JSON.stringify(initialFormData)));
        return;
    }

    // 获取SSL证书详情
    getSslsById(newValue).then((res) => {
        const sslData = res.data.value;

        // 重置表单
        Object.assign(formData, JSON.parse(JSON.stringify(initialFormData)));

        // 设置基本字段
        for (const key of Object.keys(sslData)) {
            if (key in formData) {
                formData[key] = sslData[key];
            } else if (key === "client" && typeof sslData.client === "object") {
                // 处理嵌套的client对象
                for (const clientKey of Object.keys(sslData.client)) {
                    if (clientKey in formData.client) {
                        formData.client[clientKey] = sslData.client[clientKey];
                    }
                }
            }
        }
    }).catch(err => {
        ElMessage.error(t('tips.sslLoadFailed') + ': ' + err.message);
    });
}, { immediate: true });

// 更新标签
const updateLabels = (data) => {
    formData.labels = {};
    for (const item of data) {
        if (item.key && item.value) {
            formData.labels[item.key] = item.value;
        }
    }
};

// SSL协议选项
const sslProtocolOptions = ref([
    "TLSv1",
    "TLSv1.1",
    "TLSv1.2",
    "TLSv1.3",
]);

// 添加额外证书
const addExtraCert = () => {
    if (!formData.certs) {
        formData.certs = [];
    }
    if (!formData.keys) {
        formData.keys = [];
    }
    formData.certs.push("");
    formData.keys.push("");
};

// 移除额外证书
const removeExtraCert = (index) => {
    formData.certs.splice(index, 1);
    formData.keys.splice(index, 1);
};

// 提交表单
const submitForm = () => {
    formRef.value.validate((valid) => {
        if (!valid) {
            ElMessage.error(t('tips.formValidationFailed'));
            return false;
        }

        // 获取非空值
        const { client, ...data } = getNonEmptyValues(formData);
        console.log(data);

        // 检查必填字段
        if (!data.cert) {
            ElMessage.error(t('tips.certContentRequired'));
            return false;
        }

        if (!data.key) {
            ElMessage.error(t('tips.keyContentRequired'));
            return false;
        }

        if (data.type === 'server' && (!data.snis || data.snis.length === 0)) {
            ElMessage.error(t('tips.serverCertRequiresSni'));
            return false;
        }

        // 更新现有SSL证书
        if (props.patch !== "") {
            PatchSsls(data, props.patch).then((res) => {
                ElMessage.success(t('tips.sslUpdateSuccess'));
                console.log(res);
            }).catch(err => {
                ElMessage.error(t('tips.sslUpdateFailed') + ': ' + err.message);
            });
            return;
        }

        // 创建新的SSL证书

        const id = data.id || Date.now().toString();
        createSsls(data).then((res) => {
            ElMessage.success(t('tips.sslCreateSuccess'));
            resetForm();
        }).catch(err => {
            ElMessage.error(t('tips.sslCreateFailed') + ': ' + err.message);
        });
    });
};

// 重置表单
const resetForm = () => {
    Object.assign(formData, JSON.parse(JSON.stringify(initialFormData)));
};
</script>

<style scoped>
.extra-cert-item {
    border: 1px dashed #dcdfe6;
    border-radius: 4px;
    padding: 10px;
    margin-bottom: 15px;
}

.cert-input-group {
    display: flex;
    align-items: flex-start;
}

.cert-input-group .el-input {
    flex: 1;
    margin-right: 10px;
}
</style>
